# Snowflake connection parameters
# Replace with your actual Snowflake connection details

[snowflake]
user = "YOUR_USERNAME"
password = "YOUR_PASSWORD"
account = "YOUR_ACCOUNT_IDENTIFIER"
warehouse = "RETAIL_WATCH_WH"
database = "RETAIL_WATCH_DB"
schema = "PUBLIC"
role = "YOUR_ROLE"

# Example configuration:
# user = "john_doe"
# password = "secure_password123"
# account = "xy12345.us-east-1"
# warehouse = "RETAIL_WATCH_WH"
# database = "RETAIL_WATCH_DB"
# schema = "PUBLIC"
# role = "SYSADMIN" 