# This workflow is temporarily disabled - using direct HTML deployment instead
# Rename to pages.yml to re-enable if needed

name: Deploy to GitHub Pages (Backup)

on:
  workflow_dispatch: # Only manual triggers

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - name: Build
        run: |
          mkdir -p _site
          cp index.html _site/
          cp README.md _site/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment 